### ISSUE TITLE
Notebook GPU usage

### ISSUE THREAD

**Issue by SpontaneousDuck** [canonical/notebook-operators#26] opened 2022-02-01 01:17 UTC
I just installed the Kubeflow 1.4 charm bundle on my K8s 1.21 cluster and am seeing the same issue as #10 where the Notebook spawner is saying the number of GPUS needs to be a string not an int. It looks like the PR to Kubeflow fixing this was: https://github.com/kubeflow/kubeflow/pull/5891. This PR looks like it is pushed in to Kubeflow v1.4-rc0.0 which means it should be merged in the code this charm is running. The code that is changed is on the frontend, so I am not sure if what is changed ends up being in the dashboard or jupyter-ui image.

I am running `jupyter-ui` v21 and `kubeflow-dashboard` v64 which are the latest from what I can see. I did notice that the `kubeflow-dashboard` charm is using the v1.4-rc0.0 version of the dashboard image instead of the full release image v1.4. Not sure if that is causing it?

Thanks for the help!

**Comment by DnPlas** [comment] 2022-02-02 02:17
Hi @SpontaneousDuck , thanks for reporting this. This appears to be an upstream issue that has been reported several times in [kubeflow/kubeflow](https://github.com/kubeflow/kubeflow/issues/) in our charm repos. In most of the issues they mention [kubeflow/kubeflow#5891](https://github.com/kubeflow/kubeflow/pull/5891), though that doesn't seem to resolve it.
I've came across [kubeflow/kubeflow#6014](https://github.com/kubeflow/kubeflow/issues/6014), in particular [this comment](https://github.com/kubeflow/kubeflow/issues/6014#issuecomment-881562991). After changing `form.py` as suggested there, re-building the container image, and re-deploying, the issue is not present anymore for me.
There is a [PR#6051](https://github.com/kubeflow/kubeflow/pull/6051) that introduces that exact change.

**Comment by SpontaneousDuck** [comment] 2022-02-02 20:03
Ok! Took me way too long to figure out since I am new to charms but I got it working. I was able to build my own image from kubeflow/kubeflow#6014 and use that with the `jupyter-ui` charm. Here's what I did for anyone else with the issue:

1. `git clone https://github.com/edhenry/kubeflow.git`
2. `cd kubeflow/components/crud-web-apps/`
3. `git checkout ae2b87653a29e747c27a524e2e39556ed08b43d1`
4. `docker build -t <docker_hub_credentials>/jupyter-web-app -f ./jupyter/Dockerfile .`
5. `docker push <docker_hub_credentials>/jupyter-web-app`
6. `juju remove-application jupyter-ui`
7. `juju deploy jupyter-ui --resources oci-image=<docker_hub_credentials>/jupyter-web-app`
8. `juju relate istio-pilot jupyter-ui`

If you have a single-node setup I believe you could just build the image locally and not push it to a hub. Might be wrong about that though. My setup is multi-node so this worked for me.

**Comment by DnPlas** [comment] 2022-02-03 00:22
Thanks for the update @SpontaneousDuck. We are working on a fix for Charmed Kubeflow whilst the issue in upstream gets resolved, in the meantime, we'll have to workaround it as you described.
My suggestion is, instead of using @edhenry's fork and checking out to the commit hash, you clone `kubeflow/kubeflow`, checkout to `v1.4.0` and cherry-pick the change or edit `form.py` manually and build the image (you could even use the`Makefile` provided in `kubeflow/components/crud-web-apps/jupyter`), that way you don't miss any important commits that have been added since July '21.

**Comment by DnPlas** [comment] 2022-02-08 18:27
FYI, [#6051](https://github.com/kubeflow/kubeflow/pull/6051) will get merged soon.

**Comment by phyyou** [comment] 2022-05-31 01:27
I've been create kubeflow bundle to follow this [installation instructions](https://charmed-kubeflow.io/docs/install).
but I have problem that can't creating notebook with gpu with this issue

Any updates for this? I think PR [#6051](https://github.com/kubeflow/kubeflow/pull/6051) will get merged soon. and I also hope that. but I think this issue can be more longer.

How soon will fix this issue for cherrypick .../jupyter/backend/apps/common/form.py?

**Comment by DomFleischmann** [comment] 2022-05-31 08:01
@phyyou thanks for raising this again, we will make sure this PR gets merged for the next upstream Kubeflow release (1.6) and will include it with our release too. You can expect that release to happen around July.

**Comment by DnPlas** [comment] 2022-08-10 23:09
[#6051](https://github.com/kubeflow/kubeflow/pull/6051) has been merged, this fix will be included in Charmed Kubeflow 1.6 (release soon), thus I am closing this issue. Feel free to re-open if you find any issues.

**Closed by DnPlas** 2022-08-10 23:09 UTC
Labels: bug
